// NotionTheme.swift — generated by notion-design/gen_tokens.py (mode: both)
// Bundle Inter .ttf and register in Info.plist 'Fonts provided by application'.

import SwiftUI

enum NotionTheme {
    // Type scale
    static func title() -> Font { .custom("Inter", size: 40).weight(.bold) }
    static func h1() -> Font { .custom("Inter", size: 30).weight(.semibold) }
    static func h2() -> Font { .custom("Inter", size: 24).weight(.semibold) }
    static func h3() -> Font { .custom("Inter", size: 20).weight(.semibold) }
    static func body() -> Font { .custom("Inter", size: 16).weight(.regular) }
    static func small() -> Font { .custom("Inter", size: 14).weight(.regular) }
    static func micro() -> Font { .custom("Inter", size: 12).weight(.medium) }

    // Spacing
    static let space1: CGFloat = 2
    static let space2: CGFloat = 4
    static let space3: CGFloat = 6
    static let space4: CGFloat = 8
    static let space5: CGFloat = 12
    static let space6: CGFloat = 16
    static let space7: CGFloat = 24
    static let space8: CGFloat = 32
    static let space9: CGFloat = 48
    static let space10: CGFloat = 96

    // Layout
    static let editor_max_width: CGFloat = 708
    static let sidebar_width: CGFloat = 240
    static let sidebar_width_collapsed: CGFloat = 0
    static let topbar_height: CGFloat = 45
    static let block_gutter: CGFloat = 24

    // Radius
    static let radiusSM: CGFloat = 3
    static let radiusMD: CGFloat = 4
    static let radiusLG: CGFloat = 6
    static let radiusXL: CGFloat = 8

    // Motion
    static let animDefault = Animation.timingCurve(0.2, 0, 0, 1, duration: 0.15)
    static let animSlow    = Animation.timingCurve(0.22, 1, 0.36, 1, duration: 0.20)
}

extension Color {
    static var canvas_bg: Color {
        Color.adaptive(light: Color(red: 1.0000, green: 1.0000, blue: 1.0000),
              dark:  Color(red: 0.0980, green: 0.0980, blue: 0.0980))
    }
    static var sidebar_bg: Color {
        Color.adaptive(light: Color(red: 0.9843, green: 0.9804, blue: 0.9725),
              dark:  Color(red: 0.1255, green: 0.1255, blue: 0.1255))
    }
    static var surface_overlay: Color {
        Color.adaptive(light: Color(red: 1.0000, green: 1.0000, blue: 1.0000),
              dark:  Color(red: 0.1451, green: 0.1451, blue: 0.1451))
    }
    static var text_primary: Color {
        Color.adaptive(light: Color(red: 0.2157, green: 0.2078, blue: 0.1843).opacity(1.0),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.81))
    }
    static var text_secondary: Color {
        Color.adaptive(light: Color(red: 0.4706, green: 0.4667, blue: 0.4549).opacity(1.0),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.46))
    }
    static var text_tertiary: Color {
        Color.adaptive(light: Color(red: 0.6078, green: 0.6039, blue: 0.5922).opacity(1.0),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.28))
    }
    static var text_disabled: Color {
        Color.adaptive(light: Color(red: 0.8275, green: 0.8196, blue: 0.7961).opacity(1.0),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.16))
    }
    static var divider: Color {
        Color.adaptive(light: Color(red: 0.2157, green: 0.2078, blue: 0.1843).opacity(0.09),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.094))
    }
    static var border: Color {
        Color.adaptive(light: Color(red: 0.2157, green: 0.2078, blue: 0.1843).opacity(0.16),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.13))
    }
    static var hover_bg: Color {
        Color.adaptive(light: Color(red: 0.2157, green: 0.2078, blue: 0.1843).opacity(0.03),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.055))
    }
    static var hover_bg_strong: Color {
        Color.adaptive(light: Color(red: 0.2157, green: 0.2078, blue: 0.1843).opacity(0.06),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.09))
    }
    static var selected_bg: Color {
        Color.adaptive(light: Color(red: 0.1373, green: 0.5137, blue: 0.8863).opacity(0.14),
              dark:  Color(red: 0.1373, green: 0.5137, blue: 0.8863).opacity(0.24))
    }
    static var accent_blue: Color {
        Color.adaptive(light: Color(red: 0.1373, green: 0.5137, blue: 0.8863),
              dark:  Color(red: 0.3216, green: 0.6118, blue: 0.7922))
    }
    static var accent_blue_bg: Color {
        Color.adaptive(light: Color(red: 0.1373, green: 0.5137, blue: 0.8863).opacity(0.14),
              dark:  Color(red: 0.3216, green: 0.6118, blue: 0.7922).opacity(0.2))
    }
    static var text_code: Color {
        Color.adaptive(light: Color(red: 0.9216, green: 0.3412, blue: 0.3412),
              dark:  Color(red: 1.0000, green: 0.4510, blue: 0.4118))
    }
    static var bg_code_inline: Color {
        Color.adaptive(light: Color(red: 0.5294, green: 0.5137, blue: 0.4706).opacity(0.15),
              dark:  Color(red: 1.0000, green: 1.0000, blue: 1.0000).opacity(0.08))
    }

    /// M10-Fix3：重命名为 `adaptive(light:dark:)` 静态工厂方法，避免与 swift-markdown-ui
    /// 2.4.1 内部导出的 `Color.init(light:dark:)` 产生命名歧义（编译报 ambiguous use）。
    /// 调用方从 `Color.adaptive(light: ..., dark: ...)` 迁移为 `Color.adaptive(light: ..., dark: ...)`。
    static func adaptive(light: Color, dark: Color) -> Color {
        Color(uiColor: UIColor { trait in
            trait.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
        })
    }
}
